pipeline {
    agent any
    tools {
        nodejs 'nodejs_20_12_2' // Configura la versión de Node.js instalada en Jenkins
    }
    stages {
        stage('Install Dependencies') {
            steps {
                checkout scm // Utiliza la configuración de SCM del proyecto
                bat 'npm install || exit 1' // Usa 'bat' para Windows
            }
        }

        stage('Build Project') {
            steps {
                bat 'npm run build || exit 1' // Genera la versión de producción del frontend
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat 'docker build -t haruHisomu/frontend:latest . || exit 1' // Construye la imagen Docker
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerPass', variable: 'dhpsw')]) {
                        bat 'docker login -u haruHisomu -p %dhpsw% || exit 1'
                    }
                    bat 'docker push haruHisomu/frontend:latest || exit 1'
                }
            }
        }
    }
}
